### ISSUE TITLE
HomeOwner: Edit Properties

### ISSUE THREAD

**Issue by heyhellomila** [heyhellomila/project-mender#100]
As a homeowner, I want to be able to edit properties.

Description: Homeowner will have a page where they can view their property details, edit information about the property and delete the property. Deleting the property will actually set the status of the property to inactive.

- [x] #102 API to PATCH property
- [x] #182 Refactor GET properties to accept activity status as a param
- [x] #103 Implement edit property page and view property details and integrate API and ability to delete property

[SP: 7 (Iteration 5 - 2 SP @Songtone, Iteration 7 - 5 SP @JamalG16)  ]
[Priority: High]
[Risk: Medium]
