### ISSUE TITLE
Release 2: Testing

### ISSUE THREAD

**Issue by heyhellomila** [heyhellomila/project-mender#121]
As a developer, I would like to test my application to ensure workflow and components are working correctly.

Steps:

- [x] #194 Write acceptance tests to evaluate workflow of the app found in the project's Wiki  @MickeyPa @milaroisin @daniakalomiris 
- [x] #192 Integrate Mockito in the backend project and create unit tests @JamalG16 @DanielPri 
- [x] #65 Continuous Integration with CircleCI. @milaroisin & @daniakalomiris 
- [x] #61 Code Reviews & Coverage tool for every pull request with Codacy Project Token & Istanbul. @milaroisin @daniakalomiris 
- [x] #123 Test out Code Reviews & Coverage tool for every pull request with CodeCov. @daniakalomiris 
- [x] Integrate Github Actions into repository.
- [x] Add backend build & unit tests to CI pipeline + archive test results/coverage report @JamalG16 (1 SP)

[Total SP: 10
Iteration 5 - 7 SP - 6 @daniakalomiris, 4 @milaroisin, 
Iteration 7 - 4 SP - 2 @daniakalomiris, 2 @milaroisin, 
Iteration 8 - 13 SP - 5 @DanielPri, 7 @JamalG16, 2 @daniakalomiris, 1 @MickeyPa, 1 @milaroisin  ]
[Priority: High]
[Risk: Medium]
