### ISSUE TITLE
Migrate to MySQL/TypeScript from NodeJS/MongoDB

### ISSUE THREAD

**Issue by JamalG16** [heyhellomila/project-mender#140]
Due to the need of persisting a relational data model, MySQL has been deemed as a better fit. Additionally, we will be converting to TypeScript as it is type safe and is overall more intuitive. Typescript is a superset of JS and actually compiles into JS, so we are still in fact using node, we are just using the TS language. Finally, with typescript, we will also integrate an ORM (typeorm) to map our entity objects to the tables in MySQL.

Database:
- [x] Deploy MySQL host
- [x] Create schema (work_orders, users, properties, property_types, priority_types, sector_types, status, user_types, work_order_types)
- [x] Generate tables (work_orders, users, properties, property_types, priority_types, sector_types, status, user_types, work_order_types)

Backend: 

- [x]  install typescript packages
- [x] Convert existing files to .ts files
- [x] Integrate typeorm (an ORM for typescript/mysql)
- [x] Change database connection to the new MySQL host
- [x] Create typescript models (work order, user, property, property type, priority type, sector type, status, user type, work order type)
- [x] Create a persistence layer (TDGs/Repository)
- [x] Update service classes to use persistence layer
- [x] Modify service classes to validate that fields are part of enums since this won't be done by the model in mySQL like it is done with mongo schemas
- [x] Standardize naming to use camel-casing in the backend
- [x] create DTO objects and mappers
- [x] overall refactoring for better readability/efficiency/conformity with typeorm

With the migration, new service classes had to be created and the unit tests for these classes can be found here: #192
- [x] activity status service #192 
- [x] priority type service #192 
- [x] property type service #192 
- [x] user type service #192 
- [x] work order type service #192 

Frontend:
- [x] Edit API calls to send camel-cased variables

SP: 11 (11 @JamalG16 )
Priority: High
Risk: High
