### ISSUE TITLE
As a Contractor, I would like to see my own views when I log in.

### ISSUE THREAD

**Issue by Songtone** [heyhellomila/project-mender#150]
**Epic Story**: As a Contractor, I would like to see my own views when I log in.

Extension for #149.

Steps:
- [x] Implement Model: #169 @MickeyPa @milaroisin 
- [ ] ~~Implement & integrate webscraper (no issue created)~~
- [x] Create unit tests for service class #213 @JamalG16 
- [ ] ~~Create Frontend for Contractor: #6, #109, #114, #151, #152, #153, #154, #155~~

**[Total SP: 18
Iteration 8 - 14 SP - 8 @MickeyPa 6 @milaroisin 
Iteration 9 - 4 SP @JamalG16 ]
[Priority: High]
[Risk: Medium]**

![image](https://user-images.githubusercontent.com/27459775/69765326-6e578f80-1141-11ea-8635-76a107d6a512.png)
