### ISSUE TITLE
Homeowner: Select Sector Type and Select Sector Kind

### ISSUE THREAD

**Issue by JamalG16** [heyhellomila/project-mender#158]
**Story:** As a user, I would like to select sector type and more specifically, sector kind when creating a work order and adding property information.

**Task Description:**

For work orders, the user has a 9-12 very general options to pick. These are called "types". Going a second level deeper, we have "kinds", which is something the user would also like to specify.

For properties, the user will be able to add information about their property, where they will associate sector types to their properties as well as sector kinds for specificity.

**Steps:**

- [x] #159 Include Sector Kind in the database and refactor service classes to include this new field. Also, create property sectors entity to represent relationship between properties and sectors
- [x] #163 Create API to fetch sectors by property for sector selection (if a property has a sector in DB, then the status will be changed to either ACTIVE or INACTIVE, if the property does NOT have the sector in DB, then it will be inserted as ACTIVE) 
- [x] #166 Refactor property sectors API (PATCH for a collection and not a specific id and POST should be moved to propertySectors controller)
- [x] #167 Include frontend views and flow for creating and toggling sector type/kinds for a property
- [x] #164 Modify GET work orders to accept sector type and sector kind as query parameters
- [x] #160 Refactor create work order page to include sector type AND kind

Unit tests for sector service and property sector service can be found here: #192

**[SP: (Iteration 6 - 8 SP (7 @JamalG16 , 1 @DanielPri , Iteration 8 - 3 @JamalG16 )]
[Priority: High]
[Risk: Medium]**
