### ISSUE TITLE
Integrate Mockito and Create Unit Tests

### ISSUE THREAD

**Issue by JamalG16** [heyhellomila/project-mender#192]
subtask of #121 

- [x] Integrate ts-mockito, chai and chai-as-promised in backend project @JamalG16 
- [x] Create unit tests for Activity Status Service @JamalG16 #140
- [x] Create unit tests for Priority Type Service @JamalG16 #140 
- [x] Create unit tests for Property Sector Service @JamalG16 #158
- [x] Create unit tests for Property Service @JamalG16 #70 
- [x] Create unit tests for Property Type Service @JamalG16 #140
- [x] Create unit tests for Sector Service @DanielPri #158
- [x] Create unit tests for Shopping item Service @DanielPri #88
- [x] Create unit tests for User Service @JamalG16 #9
- [x] Create unit tests for User Type Service @DanielPri #140  
- [x] Create unit tests for Work Order Service @DanielPri #4
- [x] Create unit tests for Work Order Status Service @DanielPri #177
- [x] Create unit tests for Work order Type Service @DanielPri #140 

In addition to writing the unit tests, utility methods had to be refactored to be written as classes, which can then be mocked and injected. 

- [x] Refactor AuthUtils @JamalG16 
- [x] Refactor HashUtils @JamalG16 

[SP: x (6 @JamalG16 , 5 @DanielPri )]
[Risk: Low]
[Priority: High]
