### ISSUE TITLE
Release 3: Testing

### ISSUE THREAD

**Issue by heyhellomila** [heyhellomila/project-mender#209]
Main Story: As a developer, I would like to test my application to ensure workflow and components are working correctly.

Steps:

- [x] Set up Firebase APM #210 (Closed due to extenuating circumstances beyond our control for user base)
- [x] Acceptance Tests  #208 @JamalG16 (1 SP)
- [x] Include frontend build in CI pipeline #257 @JamalG16 (3 SP)
- [x] Include Logging #259 @MickeyPa (4 SP)

[Total SP: 8]
[Priority: High]
[Risk: Low]
