### ISSUE TITLE
BUG: Location in card of Work Order always displays Upper Floor Bathroom

### ISSUE THREAD

**Issue by Songtone** [heyhellomila/project-mender#223]
**Task Description:** The work order should display correct location. Each work order should have a location attribute.

**Steps:**

- [x] Update schema
- [x] Update enums, entities, DTO, entity mapper, repository, services and controller
- [x] Update create work order form to accept location
- [x] Update work order cards to display location from props

**[Total SP: 1]
[Risk: Medium]
[Priority: High]**
