### ISSUE TITLE
User: View Own Profile

### ISSUE THREAD

**Issue by JamalG16** [heyhellomila/project-mender#31]
**Story:** As a user, I want to be able to view and edit my profile.

Steps:

- [x] Update user API: #30
- [x] Design User profile page: #29
- [x] Implement side menu: #36

**[Total SP: 23  (Iteration 4 - 3SP, Iteration 5 - 2SP, Iteration 8 - 18SP)]
[Priority: High]
[Risk: Medium]**
