### ISSUE TITLE
User: View Work Orders

### ISSUE THREAD

**Issue by JamalG16** [heyhellomila/project-mender#4]
**Story:** As a User, I want to be view all my work orders.

Steps:
- [x] Construct API: #16 
- [x] Implement Work Order View for Homeowner: #17
- [x] Implement Functional Bottom Navigator: #35
- [x] Sort by priority, sector, type and status: #179
- [x] Update API to include more details: #177 
- [x] Filter work orders: #176

Unit tests for work order service can be found here: #192

**View description**: A table with all work orders will be displayed, with pagination and a maximum of 10 work orders per page. The list of work orders will have only general information about it. The user can then click on a specific work order to open up the card with all of the work order's information.

**[Total SP: Iteration 7 - 9 (13 @daniakalomiris , 2 @MickeyPa ), Iteration 8 - 3 SP @daniakalomiris ]
[Priority:  Medium]
[Risk: Medium]**
