### ISSUE TITLE
Release 3: Documentation

### ISSUE THREAD

**Issue by heyhellomila** [heyhellomila/project-mender#51]
Subtasks:

- [x] Update logos on wiki page and readme. (@milaroisin: 0.5)
- [x] Application workflow update (@milaroisin: 0.5)
- [x] Backend - Class Diagram: #214
- [x] Frontend - Class Diagram: #240 
- [x] Milestone Documentation: [@JamalG16: 3, @milaroisin: 3]
- [x] Stakeholder Requested Documentation #249 [@milaroisin: 1]
- [x] Application Workflow Video Capture #250 [SP: 6]
- [x] Capstone Website Showcase [@milaroisin: 1]

[Total SP: 12]
[Priority: High]
[Risk: Low]
