### ISSUE TITLE
As a user, I want to include my phone number when I register.

### ISSUE THREAD

**Issue by Songtone** [heyhellomila/project-mender#83]
- [x] #86 Update model in backend & Update API to include phone number field
- [x] #80 improve registration flow and UI
- [x] #87 Include phone number field in UI

[SP:  4 (1 @Songtone , 3 @JamalG16 )]
[Risk:  Low]
[Priority: Medium]
