### ISSUE TITLE
As a user, I want to be able to access and edit my shopping list.

### ISSUE THREAD

**Issue by JamalG16** [heyhellomila/project-mender#88]
**Story:** As a user, I want to be able to access and edit my shopping list.

**Steps:**

- [x] Implement model: #89 
- [x]  Implement API to POST shopping item #90 
- [x]  Implement API to delete shopping item #91 
- [x]  Implement API to edit shopping item #92 
- [ ]  Implement frontend views/flow #93 

Unit tests for shopping item service can be found here: #192 

**[Total SP: Iteration 7 - 4 @DanielPri ]
[Priority: High]
[Risk: Medium]**
